### ISSUE TITLE
Animation is lagging and cant switch to front cam

### ISSUE THREAD

**Issue by rehantu** [gaetanozappi/Android-face-filters#1]

**Comment by gaetanozappi** [comment]
Hi @rehantu:

The project is only a prototype based on a Google project, it was to make people understand what could be done and do an experiment on it.

I know there are several problems, and at least for the moment I have no way and time to devote myself to such a project.

I hope in the future.

**Comment by rehantu** [comment]
can you suggest me some other scenario or what modification to be done in this project?

**Comment by gaetanozappi** [comment]
@rehantu: You can try to explain yourself better to understand what your problem is in this case.

It depends on what you have to do?

**Comment by rehantu** [comment]
i want to develop snapchatlike facemoji app

**Comment by gaetanozappi** [comment]
@rehantu: I understand, you who spoke for Animation is lagging is due to the consideration that you first have to analyze the image, then must find the faces and finally put the masks.
This all in real time, it's not just a photo.
Then if there are more subjects it takes more time.

However, if you are looking for lots of projects, I'll list a couple of the most interesting ones I found:

- https://github.com/SimonCherryGZ/face-landmark-android
- https://github.com/meerkat-cv/ava_preview
- https://github.com/googlesamples/android-vision

**Comment by rehantu** [comment]
thanks a lot for help.
